//! PHP backend, targeting the `FFI` extension (`FFI::load()` + generated wrapper classes).
//!
//! This deliberately reuses the C backend for ABI declarations (headers) instead of
//! re-deriving C type/ABI-name logic: PHP's `ext-ffi` consumes plain C declarations the
//! same way the C backend already emits them, so there's nothing PHP-specific about that
//! layer. This backend only adds the higher-level PHP wrapper classes on top, the same way
//! the `nanobind` backend reuses `cpp::run` and only adds Python-specific binding glue.
//!
//! Scope (v1): opaque lifecycle, structs-by-value (primitive/struct/enum fields), C-like
//! enums, `Result`-returning methods (mapped to a thrown `DiplomatError`), strings (via
//! `DiplomatWrite`), and borrowed primitive/struct slices as method *parameters*. Not yet
//! supported: owned slice/Vec *returns* (Diplomat's `SuccessType` only has `Unit`/`Write`/
//! `OutType`, so this isn't a first-class concept for any backend, not just this one),
//! callbacks, traits, and `Option<T>`.

use crate::{c, Config, ErrorStore, FileMap};
use diplomat_core::hir::{
    self, BackendAttrSupport, DocsUrlGenerator, ReturnType, StructPathLike, SuccessType, Type,
    TyPosition, TypeContext, TypeDef, TypeId,
};
use std::fmt::Write as _;

pub(crate) fn attr_support() -> BackendAttrSupport {
    let mut a = BackendAttrSupport::default();
    a.memory_sharing = true;
    a.utf8_strings = true;
    a.static_slices = true;
    a.option = false;
    a.callbacks = false;
    a.traits = false;
    a.custom_errors = false;
    a.abi_compatibles = true;
    a.struct_refs = true;
    a.free_functions = true;
    a
}

pub(crate) fn run<'tcx>(
    tcx: &'tcx TypeContext,
    config: Config,
    docs_url_gen: &'tcx DocsUrlGenerator,
) -> (FileMap, ErrorStore<'tcx, String>) {
    let files = FileMap::default();
    let errors = ErrorStore::default();

    let lib_name = config
        .shared_config
        .lib_name
        .clone()
        .expect("PHP backend requires lib_name to be set in the config");

    // Human-readable ABI headers: delegate entirely to the C backend and copy them into
    // include/ for reference (and for any real C consumer of the same dylib). PHP itself
    // does NOT parse these: PHP's `FFI::cdef()` parser only understands a restricted C
    // subset (no `static_assert`, no `uint_least16_t`-style stdint aliases, no macros),
    // so reusing the C backend's literal header text — written for a real C compiler —
    // isn't reliable. Instead `gen_cdefs` below builds a minimal, PHP-parser-safe
    // declaration set directly from the same HIR, restricted to what v1 supports.
    let (c_files, c_errors) = c::run(tcx, &config, docs_url_gen);
    errors.errors.borrow_mut().extend(c_errors.errors.take());
    for (name, content) in c_files.take_files() {
        files.add_file(format!("include/{name}"), content);
    }

    let cdefs;
    {
        let ctx = Ctx { tcx, errors: &errors };
        cdefs = ctx.gen_cdefs();
        for (id, ty) in tcx.all_types() {
            if ty.attrs().disable {
                continue;
            }
            let _guard = errors.set_context_ty(ty.name().as_str().into());
            let php = match ty {
                TypeDef::Opaque(o) => ctx.gen_opaque(id, o),
                TypeDef::Struct(s) => ctx.gen_struct(id, s.name.as_str(), s.fields.iter()),
                TypeDef::OutStruct(s) => ctx.gen_struct(id, s.name.as_str(), s.fields.iter()),
                TypeDef::Enum(e) => ctx.gen_enum(e),
                _ => continue,
            };
            files.add_file(format!("{}.php", ty.name().as_str()), php);
        }
    }

    files.add_file("Lib.php".to_string(), gen_lib_php(&lib_name, &cdefs));
    files.add_file("DiplomatError.php".to_string(), gen_error_php());

    let mut index = String::new();
    let _ = writeln!(index, "<?php");
    let _ = writeln!(index, "// generated by diplomat-tool (php backend)");
    let _ = writeln!(index, "require_once __DIR__ . '/Lib.php';");
    let _ = writeln!(index, "require_once __DIR__ . '/DiplomatError.php';");
    for (_, ty) in tcx.all_types() {
        if ty.attrs().disable {
            continue;
        }
        let _ = writeln!(
            index,
            "require_once __DIR__ . '/{}.php';",
            ty.name().as_str()
        );
    }
    files.add_file("index.php".to_string(), index);

    (files, errors)
}

struct Ctx<'cx, 'tcx> {
    tcx: &'tcx TypeContext,
    errors: &'cx ErrorStore<'tcx, String>,
}

fn gen_lib_php(lib_name: &str, cdefs: &str) -> String {
    let env_var = format!("{}_LIBRARY_PATH", lib_name.to_uppercase());
    format!(
        r#"<?php
namespace Stencil;

final class Lib {{
    private static ?\FFI $ffi = null;
    private static ?string $libraryPath = null;

    const CDEFS = <<<'PHP_STENCIL_CDEFS_EOT'
{cdefs}
PHP_STENCIL_CDEFS_EOT;

    /// Call this once, before touching any generated class, with the path to the
    /// compiled `{lib_name}` shared library (.so/.dylib/.dll). Falls back to the
    /// {env_var} environment variable if never called explicitly.
    public static function init(string $libraryPath): void {{
        if (self::$ffi !== null) {{
            throw new \RuntimeException('Stencil\\Lib::init() called after the library was already loaded');
        }}
        self::$libraryPath = $libraryPath;
    }}

    public static function ffi(): \FFI {{
        if (self::$ffi === null) {{
            $path = self::$libraryPath ?? getenv('{env_var}');
            if ($path === false || $path === null) {{
                throw new \RuntimeException(
                    'Stencil\\Lib: no library path set — call Lib::init($path) or set the {env_var} environment variable'
                );
            }}
            self::$ffi = \FFI::cdef(self::CDEFS, $path);
        }}
        return self::$ffi;
    }}

    public static function readAndFreeWrite(\FFI\CData $write): string {{
        $ffi = self::ffi();
        $len = $ffi->diplomat_buffer_write_len($write);
        $bytes = $ffi->diplomat_buffer_write_get_bytes($write);
        $str = \FFI::string($bytes, $len);
        $ffi->diplomat_buffer_write_destroy($write);
        return $str;
    }}
}}
"#
    )
}

fn gen_error_php() -> String {
    r#"<?php
namespace Stencil;

/// Thrown for every fallible generated method. $errorType/$errorName tell you which
/// generated enum this came from (e.g. "SchematicError", "OutOfBounds"); $errorValue is
/// the raw int discriminant, for callers that want to switch on it without string matching.
final class DiplomatError extends \Exception {
    public function __construct(
        public readonly string $errorType,
        public readonly int $errorValue,
        public readonly string $errorName,
    ) {
        parent::__construct("{$errorType}::{$errorName}");
    }
}
"#
    .to_string()
}

impl<'cx, 'tcx> Ctx<'cx, 'tcx> {
    /// Builds the `FFI::cdef()` declaration string. Hand-rolled from the HIR rather than
    /// reusing the C backend's header text: PHP's cdef parser only understands a
    /// restricted C subset (no `static_assert`, no `uint_least16_t`-style stdint aliases,
    /// no macros), so the real headers — written for an actual C compiler — don't parse.
    /// This only needs to match the *ABI layout* the real headers describe, not their
    /// exact spelling: FFI calls are resolved by symbol name and matched by memory
    /// layout, not by type name, so a parallel, simplified declaration set is safe as
    /// long as it's internally consistent.
    fn gen_cdefs(&self) -> String {
        let mut out = String::new();
        out.push_str(
            "typedef struct DiplomatWrite DiplomatWrite;\n\
             DiplomatWrite* diplomat_buffer_write_create(size_t cap);\n\
             char* diplomat_buffer_write_get_bytes(DiplomatWrite* t);\n\
             size_t diplomat_buffer_write_len(DiplomatWrite* t);\n\
             void diplomat_buffer_write_destroy(DiplomatWrite* t);\n\n",
        );
        // Primitive slice views: fixed set, matching diplomat_runtime.h's
        // MAKE_SLICES_AND_OPTIONS instantiations. Declaring all of them unconditionally
        // is cheap (unused typedefs cost nothing) and avoids tracking real usage.
        for (prim_c_ty, view_name) in [
            ("int8_t", "I8"),
            ("uint8_t", "U8"),
            ("int16_t", "I16"),
            ("uint16_t", "U16"),
            ("int32_t", "I32"),
            ("uint32_t", "U32"),
            ("int64_t", "I64"),
            ("uint64_t", "U64"),
            ("intptr_t", "Isize"),
            ("size_t", "Usize"),
            ("float", "F32"),
            ("double", "F64"),
            ("bool", "Bool"),
        ] {
            let _ = writeln!(
                out,
                "typedef struct Diplomat{view_name}View {{ const {prim_c_ty}* data; size_t len; }} Diplomat{view_name}View;"
            );
        }
        out.push_str("typedef struct DiplomatStringView { const char* data; size_t len; } DiplomatStringView;\n");
        out.push('\n');

        for (_, ty) in self.tcx.all_types() {
            if ty.attrs().disable {
                continue;
            }
            if let TypeDef::Enum(def) = ty {
                let name = def.name.as_str();
                let _ = write!(out, "typedef enum {name} {{ ");
                for v in &def.variants {
                    let _ = write!(out, "{name}_{} = {}, ", v.name.as_str(), v.discriminant);
                }
                let _ = writeln!(out, "}} {name};");
            }
        }
        out.push('\n');

        for (_, ty) in self.tcx.all_types() {
            if ty.attrs().disable {
                continue;
            }
            let (name, fields): (&str, Vec<(&str, Option<String>)>) = match ty {
                TypeDef::Struct(s) => (
                    s.name.as_str(),
                    s.fields
                        .iter()
                        .map(|f| (f.name.as_str(), self.c_type_name(&f.ty)))
                        .collect(),
                ),
                TypeDef::OutStruct(s) => (
                    s.name.as_str(),
                    s.fields
                        .iter()
                        .map(|f| (f.name.as_str(), self.c_type_name(&f.ty)))
                        .collect(),
                ),
                _ => continue,
            };
            let _ = write!(out, "typedef struct {name} {{ ");
            for (fname, cty) in &fields {
                match cty {
                    Some(cty) => {
                        let _ = write!(out, "{cty} {fname}; ");
                    }
                    None => self.errors.push_error(format!(
                        "php backend: unsupported field type on struct {name}::{fname}"
                    )),
                }
            }
            let _ = writeln!(out, "}} {name};");
            let _ = writeln!(
                out,
                "typedef struct Diplomat{name}View {{ const {name}* data; size_t len; }} Diplomat{name}View;"
            );
        }
        out.push('\n');

        for (_, ty) in self.tcx.all_types() {
            if ty.attrs().disable {
                continue;
            }
            if let TypeDef::Opaque(def) = ty {
                let _ = writeln!(out, "typedef struct {name} {name};", name = def.name.as_str());
            }
        }
        out.push('\n');

        for (_, ty) in self.tcx.all_types() {
            if ty.attrs().disable {
                continue;
            }
            if let TypeDef::Opaque(def) = ty {
                for method in def.methods.iter() {
                    if method.attrs.disable {
                        continue;
                    }
                    self.gen_cdef_method(&mut out, def.name.as_str(), method);
                }
                let _ = writeln!(
                    out,
                    "void {}({}* self);",
                    def.dtor_abi_name.as_str(),
                    def.name.as_str()
                );
            }
        }

        out
    }

    fn gen_cdef_method(&self, out: &mut String, owner_name: &str, method: &'tcx hir::Method) {
        let mut params = Vec::new();
        if method.param_self.is_some() {
            params.push(format!("{owner_name}* self"));
        }
        for param in &method.params {
            let Some(cty) = self.c_param_type_name(&param.ty) else {
                // Unsupported parameter type — php_param_hint() will also return None
                // for it, so gen_method() skips this method on the PHP side. Skip the
                // cdef declaration too so nothing calls into an undeclared symbol.
                return;
            };
            params.push(format!("{cty} {}", param.name.as_str()));
        }

        let mut result_typedef = None;
        let return_ty = match &method.output {
            ReturnType::Infallible(SuccessType::Unit) => "void".to_string(),
            ReturnType::Infallible(SuccessType::Write) => {
                params.push("DiplomatWrite* write".to_string());
                "void".to_string()
            }
            ReturnType::Infallible(SuccessType::OutType(ref ty)) => {
                let Some(cty) = self.c_type_name(ty) else {
                    return;
                };
                cty
            }
            ReturnType::Fallible(ref ok, ref err) => {
                let ok_field = match ok {
                    SuccessType::Write => {
                        params.push("DiplomatWrite* write".to_string());
                        None
                    }
                    SuccessType::Unit => None,
                    SuccessType::OutType(ref ty) => match self.c_type_name(ty) {
                        Some(cty) => Some(cty),
                        None => return,
                    },
                    _ => unreachable!("unknown AST/HIR variant"),
                };
                let err_field = match err {
                    Some(ty) => match self.c_type_name(ty) {
                        Some(cty) => Some(cty),
                        None => return,
                    },
                    None => None,
                };
                let result_name = format!("{}_result", method.abi_name.as_str());
                let mut def = format!("typedef struct {result_name} {{ union {{ ");
                if let Some(ok_ty) = &ok_field {
                    let _ = write!(def, "{ok_ty} ok; ");
                }
                if let Some(err_ty) = &err_field {
                    let _ = write!(def, "{err_ty} err; ");
                }
                let _ = writeln!(def, "}}; bool is_ok; }} {result_name};");
                result_typedef = Some(def);
                result_name
            }
            ReturnType::Nullable(_) => return,
            _ => unreachable!("unknown AST/HIR variant"),
        };

        if let Some(def) = result_typedef {
            out.push_str(&def);
        }
        let _ = writeln!(
            out,
            "{return_ty} {}({});",
            method.abi_name.as_str(),
            params.join(", ")
        );
    }

    fn c_type_name<P: TyPosition>(&self, ty: &Type<P>) -> Option<String> {
        Some(match ty {
            Type::Primitive(prim) => primitive_c_type(*prim).to_string(),
            Type::Enum(e) => self
                .tcx
                .resolve_type(e.tcx_id.into())
                .name()
                .as_str()
                .to_string(),
            Type::Struct(s) => self.tcx.resolve_type(s.id()).name().as_str().to_string(),
            Type::Opaque(o) => format!(
                "{}*",
                self.tcx.resolve_type(o.tcx_id.into()).name().as_str()
            ),
            _ => return None,
        })
    }

    /// Like `c_type_name`, but also accepts slices (view-struct-by-value) — slices are
    /// only ever valid in parameter position, never as a field or return type in v1.
    fn c_param_type_name<P: TyPosition>(&self, ty: &Type<P>) -> Option<String> {
        if let Type::Slice(slice) = ty {
            return Some(match slice {
                hir::Slice::Primitive(_, prim) => {
                    format!("Diplomat{}View", primitive_c_type_name_for_view(*prim))
                }
                hir::Slice::Struct(_, st) => {
                    let st_name = self.tcx.resolve_type(st.id()).name().as_str().to_string();
                    format!("Diplomat{st_name}View")
                }
                hir::Slice::Str(..) => "DiplomatStringView".to_string(),
                _ => return None,
            });
        }
        self.c_type_name(ty)
    }

    fn gen_enum(&self, def: &'tcx hir::EnumDef) -> String {
        let name = def.name.as_str();
        let mut out = String::new();
        let _ = writeln!(out, "<?php");
        let _ = writeln!(out, "namespace Stencil;");
        let _ = writeln!(out);
        let _ = writeln!(out, "final class {name} {{");
        for variant in &def.variants {
            let _ = writeln!(
                out,
                "    const {} = {};",
                variant.name.as_str(),
                variant.discriminant
            );
        }
        let _ = writeln!(out);
        let _ = writeln!(out, "    public static function name(int $value): string {{");
        let _ = writeln!(out, "        return match ($value) {{");
        for variant in &def.variants {
            let _ = writeln!(
                out,
                "            self::{} => '{}',",
                variant.name.as_str(),
                variant.name.as_str()
            );
        }
        let _ = writeln!(out, "            default => \"Unknown({{$value}})\",");
        let _ = writeln!(out, "        }};");
        let _ = writeln!(out, "    }}");
        let _ = writeln!(out, "}}");
        out
    }

    fn gen_struct<'a, P: TyPosition + 'a>(
        &self,
        id: TypeId,
        name: &str,
        fields: impl Iterator<Item = &'a hir::StructField<P>> + 'a,
    ) -> String
    where
        'tcx: 'a,
    {
        let fields: Vec<_> = fields.collect();
        let mut out = String::new();
        let _ = writeln!(out, "<?php");
        let _ = writeln!(out, "namespace Stencil;");
        let _ = writeln!(out);
        let _ = writeln!(out, "final class {name} {{");
        let params = fields
            .iter()
            .map(|f| format!("public {} ${}", self.php_scalar_hint(&f.ty), f.name.as_str()))
            .collect::<Vec<_>>()
            .join(", ");
        let _ = writeln!(out, "    public function __construct({params}) {{}}");
        let _ = writeln!(out);

        let _ = writeln!(out, "    public static function fromFFI($s): self {{");
        let args = fields
            .iter()
            .map(|f| self.from_ffi_field_expr(&f.ty, &format!("$s->{}", f.name.as_str())))
            .collect::<Vec<_>>()
            .join(", ");
        let _ = writeln!(out, "        return new self({args});");
        let _ = writeln!(out, "    }}");
        let _ = writeln!(out);

        let _ = writeln!(out, "    public function toFFI() {{");
        let _ = writeln!(out, "        $s = Lib::ffi()->new('{name}');");
        for f in &fields {
            let fname = f.name.as_str();
            let value = self.to_ffi_field_expr(&f.ty, &format!("$this->{fname}"));
            let _ = writeln!(out, "        $s->{fname} = {value};");
        }
        let _ = writeln!(out, "        return $s;");
        let _ = writeln!(out, "    }}");
        let _ = writeln!(out, "}}");
        let _ = id; // reserved for future namespacing use
        out
    }

    fn gen_opaque(&self, id: TypeId, def: &'tcx hir::OpaqueDef) -> String {
        let name = def.name.as_str();
        let mut out = String::new();
        let _ = writeln!(out, "<?php");
        let _ = writeln!(out, "namespace Stencil;");
        let _ = writeln!(out);
        let _ = writeln!(out, "final class {name} {{");
        let _ = writeln!(out, "    /** @internal */");
        let _ = writeln!(out, "    public \\FFI\\CData $ptr;");
        let _ = writeln!(out, "    private bool $owned;");
        let _ = writeln!(out);
        let _ = writeln!(out, "    /** @internal */");
        let _ = writeln!(
            out,
            "    public function __construct(\\FFI\\CData $ptr, bool $owned) {{"
        );
        let _ = writeln!(out, "        $this->ptr = $ptr;");
        let _ = writeln!(out, "        $this->owned = $owned;");
        let _ = writeln!(out, "    }}");
        let _ = writeln!(out);

        for method in def.methods.iter() {
            if method.attrs.disable {
                continue;
            }
            let _guard = self.errors.set_context_method(method.name.as_str().into());
            self.gen_method(&mut out, name, method);
        }

        let _ = writeln!(out, "    public function __destruct() {{");
        let _ = writeln!(out, "        if ($this->owned) {{");
        let _ = writeln!(
            out,
            "            Lib::ffi()->{}($this->ptr);",
            def.dtor_abi_name.as_str()
        );
        let _ = writeln!(out, "        }}");
        let _ = writeln!(out, "    }}");
        let _ = writeln!(out, "}}");
        let _ = id;
        out
    }

    fn gen_method(&self, out: &mut String, owner_name: &str, method: &'tcx hir::Method) {
        let is_static = method.param_self.is_none();
        let php_name = to_camel_case(method.name.as_str());

        let mut php_params = Vec::new();
        let mut call_args = Vec::new();
        let mut setup = String::new();
        if !is_static {
            call_args.push("$this->ptr".to_string());
        }
        for (i, param) in method.params.iter().enumerate() {
            let pname = format!("${}", param.name.as_str());
            match self.php_param_hint(&param.ty) {
                Some(hint) => php_params.push(format!("{hint} {pname}")),
                None => {
                    self.errors.push_error(format!(
                        "php backend: unsupported parameter type for {owner_name}::{}",
                        method.name.as_str()
                    ));
                    return;
                }
            }
            call_args.push(self.to_ffi_call_arg(&mut setup, &param.ty, &pname, i));
        }

        let visibility = if is_static { "public static" } else { "public" };
        let _ = writeln!(
            out,
            "    {visibility} function {php_name}({}) {{",
            php_params.join(", ")
        );
        out.push_str(&setup);

        match &method.output {
            ReturnType::Infallible(SuccessType::Unit) => {
                let _ = writeln!(
                    out,
                    "        Lib::ffi()->{}({});",
                    method.abi_name.as_str(),
                    call_args.join(", ")
                );
            }
            ReturnType::Infallible(SuccessType::Write) => {
                let _ = writeln!(out, "        $write = Lib::ffi()->diplomat_buffer_write_create(0);");
                call_args.push("$write".to_string());
                let _ = writeln!(
                    out,
                    "        Lib::ffi()->{}({});",
                    method.abi_name.as_str(),
                    call_args.join(", ")
                );
                let _ = writeln!(out, "        return Lib::readAndFreeWrite($write);");
            }
            ReturnType::Infallible(SuccessType::OutType(ref ty)) => {
                let _ = writeln!(
                    out,
                    "        $ret = Lib::ffi()->{}({});",
                    method.abi_name.as_str(),
                    call_args.join(", ")
                );
                let _ = writeln!(out, "        return {};", self.from_ffi_call_result(ty, "$ret"));
            }
            ReturnType::Fallible(ref ok, ref err) => {
                let uses_write = matches!(ok, SuccessType::Write);
                if uses_write {
                    let _ = writeln!(
                        out,
                        "        $write = Lib::ffi()->diplomat_buffer_write_create(0);"
                    );
                    call_args.push("$write".to_string());
                }
                let _ = writeln!(
                    out,
                    "        $result = Lib::ffi()->{}({});",
                    method.abi_name.as_str(),
                    call_args.join(", ")
                );
                let _ = writeln!(out, "        if (!$result->is_ok) {{");
                match err {
                    Some(err_ty) => {
                        if let Some(err_name) = self.enum_type_name(err_ty) {
                            let _ = writeln!(
                                out,
                                "            throw new DiplomatError('{err_name}', $result->err, {err_name}::name($result->err));"
                            );
                        } else {
                            let _ = writeln!(
                                out,
                                "            throw new DiplomatError('{owner_name}', 0, 'error');"
                            );
                        }
                    }
                    None => {
                        let _ = writeln!(
                            out,
                            "            throw new DiplomatError('{owner_name}', 0, 'error');"
                        );
                    }
                }
                let _ = writeln!(out, "        }}");
                match ok {
                    SuccessType::Unit => {}
                    SuccessType::Write => {
                        let _ = writeln!(out, "        return Lib::readAndFreeWrite($write);");
                    }
                    SuccessType::OutType(ref ty) => {
                        let _ = writeln!(
                            out,
                            "        return {};",
                            self.from_ffi_call_result(ty, "$result->ok")
                        );
                    }
                    _ => unreachable!("unknown AST/HIR variant"),
                }
            }
            ReturnType::Nullable(_) => {
                self.errors.push_error(format!(
                    "php backend: Option-returning methods aren't supported yet ({owner_name}::{})",
                    method.name.as_str()
                ));
            }
            _ => unreachable!("unknown AST/HIR variant"),
        }

        let _ = writeln!(out, "    }}");
        let _ = writeln!(out);
    }

    /// The PHP-side type hint for a method parameter, or `None` if unsupported in v1.
    fn php_param_hint<P: hir::TyPosition>(&self, ty: &Type<P>) -> Option<String> {
        Some(match ty {
            Type::Primitive(_) => "".to_string(),
            Type::Opaque(_) | Type::Struct(_) => "".to_string(),
            Type::Enum(_) => "int".to_string(),
            Type::Slice(hir::Slice::Str(..)) => "string".to_string(),
            Type::Slice(hir::Slice::Primitive(..)) => "array".to_string(),
            Type::Slice(hir::Slice::Struct(..)) => "array".to_string(),
            _ => return None,
        })
    }

    /// PHP expression converting a PHP-side call argument into what the FFI call needs.
    /// May append setup statements to `setup` (executed before the FFI call) — needed
    /// for slices, which must build a backing array *and* a `data`/`len` view struct
    /// pointing into it, both of which need to stay alive as real local variables for
    /// the duration of the call (an inline expression's temporaries would be freed by
    /// PHP's refcounting before the call that reads through the pointer even happens).
    fn to_ffi_call_arg<P: hir::TyPosition>(
        &self,
        setup: &mut String,
        ty: &Type<P>,
        pname: &str,
        index: usize,
    ) -> String {
        match ty {
            Type::Primitive(_) => pname.to_string(),
            Type::Enum(_) => pname.to_string(),
            Type::Opaque(_) => format!("{pname}->ptr"),
            Type::Struct(_) => format!("{pname}->toFFI()"),
            Type::Slice(hir::Slice::Str(..)) => {
                let buf = format!("$__buf{index}");
                let view = format!("$__view{index}");
                let _ = writeln!(setup, "        $__n{index} = strlen({pname});");
                let _ = writeln!(
                    setup,
                    "        {buf} = Lib::ffi()->new(\"uint8_t[\" . $__n{index} . \"]\", false);"
                );
                let _ = writeln!(
                    setup,
                    "        \\FFI::memcpy({buf}, {pname}, $__n{index});"
                );
                let _ = writeln!(setup, "        {view} = Lib::ffi()->new('DiplomatStringView');");
                let _ = writeln!(
                    setup,
                    "        {view}->data = $__n{index} > 0 ? Lib::ffi()->cast('const char*', \\FFI::addr({buf}[0])) : null;"
                );
                let _ = writeln!(setup, "        {view}->len = $__n{index};");
                view
            }
            Type::Slice(hir::Slice::Primitive(_, prim)) => {
                let c_ty = primitive_c_type(*prim);
                let arr = format!("$__arr{index}");
                let view = format!("$__view{index}");
                let _ = writeln!(setup, "        $__n{index} = count({pname});");
                let _ = writeln!(
                    setup,
                    "        {arr} = Lib::ffi()->new(\"{c_ty}[\" . $__n{index} . \"]\", false);"
                );
                let _ = writeln!(
                    setup,
                    "        foreach ({pname} as $__i{index} => $__v{index}) {{ {arr}[$__i{index}] = $__v{index}; }}"
                );
                let _ = writeln!(setup, "        {view} = Lib::ffi()->new('Diplomat{}View');", primitive_c_type_name_for_view(*prim));
                let _ = writeln!(
                    setup,
                    "        {view}->data = $__n{index} > 0 ? \\FFI::addr({arr}[0]) : null;"
                );
                let _ = writeln!(setup, "        {view}->len = $__n{index};");
                view
            }
            Type::Slice(hir::Slice::Struct(_, ref st)) => {
                let st_name = self.tcx.resolve_type(st.id()).name().as_str().to_string();
                let arr = format!("$__arr{index}");
                let view = format!("$__view{index}");
                let _ = writeln!(setup, "        $__n{index} = count({pname});");
                let _ = writeln!(
                    setup,
                    "        {arr} = Lib::ffi()->new(\"{st_name}[\" . $__n{index} . \"]\", false);"
                );
                let _ = writeln!(
                    setup,
                    "        foreach ({pname} as $__i{index} => $__v{index}) {{ {arr}[$__i{index}] = $__v{index}->toFFI(); }}"
                );
                let _ = writeln!(setup, "        {view} = Lib::ffi()->new('Diplomat{st_name}View');");
                let _ = writeln!(
                    setup,
                    "        {view}->data = $__n{index} > 0 ? \\FFI::addr({arr}[0]) : null;"
                );
                let _ = writeln!(setup, "        {view}->len = $__n{index};");
                view
            }
            _ => pname.to_string(),
        }
    }

    /// PHP expression converting an FFI return value into the PHP-side value.
    fn from_ffi_call_result(&self, ty: &hir::OutType, expr: &str) -> String {
        match ty {
            Type::Primitive(_) => expr.to_string(),
            Type::Enum(_) => expr.to_string(),
            Type::Struct(ref st) => {
                let st_name = self.tcx.resolve_type(st.id()).name().as_str().to_string();
                format!("{st_name}::fromFFI({expr})")
            }
            Type::Opaque(ref op) => {
                let op_name = self
                    .tcx
                    .resolve_type(op.tcx_id.into())
                    .name()
                    .as_str()
                    .to_string();
                format!("new {op_name}({expr}, true)")
            }
            _ => expr.to_string(),
        }
    }

    fn from_ffi_field_expr<P: TyPosition>(&self, ty: &Type<P>, expr: &str) -> String {
        match ty {
            Type::Primitive(_) => expr.to_string(),
            Type::Enum(_) => expr.to_string(),
            Type::Struct(ref st) => {
                let st_name = self.tcx.resolve_type(st.id()).name().as_str().to_string();
                format!("{st_name}::fromFFI({expr})")
            }
            _ => expr.to_string(),
        }
    }

    fn to_ffi_field_expr<P: TyPosition>(&self, ty: &Type<P>, expr: &str) -> String {
        match ty {
            Type::Primitive(_) => expr.to_string(),
            Type::Enum(_) => expr.to_string(),
            Type::Struct(_) => format!("{expr}->toFFI()"),
            _ => expr.to_string(),
        }
    }

    fn php_scalar_hint<P: TyPosition>(&self, ty: &Type<P>) -> &'static str {
        match ty {
            Type::Primitive(hir::PrimitiveType::Bool) => "bool",
            Type::Primitive(hir::PrimitiveType::Float(_)) => "float",
            Type::Primitive(_) => "int",
            Type::Enum(_) => "int",
            _ => "mixed",
        }
    }

    fn enum_type_name(&self, ty: &hir::OutType) -> Option<String> {
        match ty {
            Type::Enum(ref e) => Some(
                self.tcx
                    .resolve_type(e.tcx_id.into())
                    .name()
                    .as_str()
                    .to_string(),
            ),
            _ => None,
        }
    }
}

fn primitive_c_type(prim: hir::PrimitiveType) -> &'static str {
    use hir::{FloatType, IntSizeType, IntType, PrimitiveType};
    match prim {
        PrimitiveType::Bool => "bool",
        PrimitiveType::Char => "char32_t",
        PrimitiveType::Int(IntType::I8) | PrimitiveType::Ordering => "int8_t",
        PrimitiveType::Int(IntType::U8) | PrimitiveType::Byte => "uint8_t",
        PrimitiveType::Int(IntType::I16) => "int16_t",
        PrimitiveType::Int(IntType::U16) => "uint16_t",
        PrimitiveType::Int(IntType::I32) => "int32_t",
        PrimitiveType::Int(IntType::U32) => "uint32_t",
        PrimitiveType::Int(IntType::I64) => "int64_t",
        PrimitiveType::Int(IntType::U64) => "uint64_t",
        PrimitiveType::Int128(_) => "int64_t",
        PrimitiveType::IntSize(IntSizeType::Isize) => "intptr_t",
        PrimitiveType::IntSize(IntSizeType::Usize) => "size_t",
        PrimitiveType::Float(FloatType::F32) => "float",
        PrimitiveType::Float(FloatType::F64) => "double",
    }
}

/// The `Diplomat{Name}View` suffix used for primitive slice views — must match the
/// pre-instantiated `MAKE_SLICES_AND_OPTIONS` names in diplomat_runtime.h.
fn primitive_c_type_name_for_view(prim: hir::PrimitiveType) -> &'static str {
    use hir::{FloatType, IntSizeType, IntType, PrimitiveType};
    match prim {
        PrimitiveType::Bool => "Bool",
        PrimitiveType::Char => "Char",
        PrimitiveType::Int(IntType::I8) | PrimitiveType::Ordering => "I8",
        PrimitiveType::Int(IntType::U8) | PrimitiveType::Byte => "U8",
        PrimitiveType::Int(IntType::I16) => "I16",
        PrimitiveType::Int(IntType::U16) => "U16",
        PrimitiveType::Int(IntType::I32) => "I32",
        PrimitiveType::Int(IntType::U32) => "U32",
        PrimitiveType::Int(IntType::I64) => "I64",
        PrimitiveType::Int(IntType::U64) => "U64",
        PrimitiveType::Int128(_) => "I64",
        PrimitiveType::IntSize(IntSizeType::Isize) => "Isize",
        PrimitiveType::IntSize(IntSizeType::Usize) => "Usize",
        PrimitiveType::Float(FloatType::F32) => "F32",
        PrimitiveType::Float(FloatType::F64) => "F64",
    }
}

fn to_camel_case(name: &str) -> String {
    let mut out = String::new();
    let mut upper_next = false;
    for (i, c) in name.chars().enumerate() {
        if c == '_' {
            upper_next = true;
        } else if i == 0 {
            out.push(c.to_ascii_lowercase());
        } else if upper_next {
            out.push(c.to_ascii_uppercase());
            upper_next = false;
        } else {
            out.push(c);
        }
    }
    out
}
